
name: Morales Bot - Create PR GitHub

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Get branch name
        shell: bash
        run: echo 'The branch name is' ${{ steps.extract_branch.outputs.branch }}
        id: name_branch
        
      - name: Create Pull Request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch:  ${{ steps.extract_branch.outputs.branch }}
          target_branch: ${{ inputs.branch }}
          draft: false